name: release-it
description: 'Release with release it'

branding:
  icon: 'airplay'
  color: 'red'

inputs:
  working-directory:
    description: working directory
    default: '.'
  app-key:
    description: github app private key
  app-id:
    description: github app id
  app-email:
    description: github app no reply email
  app:
    description: github app name

runs:
  using: 'composite'
  steps:
    - uses: emocional/action-git-config@main
      with:
        app: ${{ inputs.app }}
        app-id: ${{ inputs.app-id }}
        app-email: ${{ inputs.app-email }}
        app-key: ${{ inputs.app-key }}
      id: get_token

    - shell: sh
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.working-directory }}

    - name: Release
      run: pnpm release-it --ci
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      env:
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
        NODE_AUTH_TOKEN: ${{ steps.get_token.outputs.token }}

