name: release-it
description: 'Release with release it'

branding:
  icon: 'airplay'
  color: 'red'

inputs:
  working-directory:
    description: working directory
    default: '.'

runs:
  using: 'composite'
  steps:
    - uses: emocional/action-git-config@main
      id: get_token

    - shell: sh
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.working-directory }}

    - name: Release
      run: pnpm release-it --ci
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      env:
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
        NODE_AUTH_TOKEN: ${{ steps.get_token.outputs.token }}

